-- GridShift Solutions — product seed
-- GENERATED from src/data/products.json by scripts/generate-seed.mjs. Do not edit by hand.

insert into public.products
  (id, slug, name, category, manufacturer, tagline, description, price_cents, compare_at_price_cents, rating, badge, tax_credit_eligible, power_output_w, capacity_kwh, specs, key_specs, image, images, stock, featured)
values
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101001'::uuid, 'gs-450-mono-max', 'GS-450 Mono Max', 'panels'::public.product_category, 'GridShift', 'Monocrystalline PERC panel engineered for maximum residential yield.', 'Optimized for low-light performance and extreme weather durability. Engineered with patented half-cut cell technology to minimize energy loss across the string, with a reinforced anodized frame rated for 5400Pa snow load.', 38900, null, 4.9, 'HIGH EFFICIENCY', true, 450, null, '[{"label":"Peak Power","value":"450 Watts"},{"label":"Efficiency","value":"22.8%"},{"label":"Cell Type","value":"N-Type Monocrystalline"},{"label":"Weight","value":"23.5 kg (51.8 lbs)"},{"label":"Frame","value":"Anodized Aluminum"},{"label":"Warranty","value":"25 Year Linear"}]'::jsonb, '[{"label":"Output","value":"450W"},{"label":"Efficiency","value":"22.8%"},{"label":"Warranty","value":"25y"}]'::jsonb, '/images/products/panel-mono.svg', '["/images/products/panel-mono.svg","/images/products/panel-detail.svg","/images/products/mounting-kit.svg"]'::jsonb, 120, true),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101002'::uuid, 'shiftcell-10-5', 'ShiftCell 10.5', 'batteries'::public.product_category, 'GridShift', 'LFP storage module with integrated BMS. Scalable to 42kWh.', 'Lithium iron phosphate storage module with integrated battery management and smart thermal regulation. Stack up to four modules for whole-home backup with seamless grid-outage transfer in under 20 milliseconds.', 624000, null, 4.8, 'BEST VALUE', true, 5000, 10.5, '[{"label":"Usable Capacity","value":"10.5 kWh"},{"label":"Cycle Life","value":"6,000 cycles"},{"label":"Continuous Output","value":"5.0 kW"},{"label":"Chemistry","value":"LiFePO4 (LFP)"},{"label":"Transfer Time","value":"< 20 ms"},{"label":"Warranty","value":"10 Year / 6,000 cycles"}]'::jsonb, '[{"label":"Capacity","value":"10.5kWh"},{"label":"Cycles","value":"6,000"},{"label":"Output","value":"5.0kW"}]'::jsonb, '/images/products/battery-wall.svg', '["/images/products/battery-wall.svg","/images/products/battery-rack.svg"]'::jsonb, 40, true),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101003'::uuid, 'gs-bifacial-550', 'GS-Bifacial 550', 'panels'::public.product_category, 'GridShift', 'Bifacial technology captures reflected light, increasing total yield.', 'Dual-glass bifacial module that harvests reflected irradiance from the rear face, delivering up to 25% additional gain over ground-mounted and high-albedo installations. Rated for 5400Pa front load.', 51200, null, 5, 'NEW TECH', true, 550, null, '[{"label":"Peak Power","value":"550 Watts"},{"label":"Bifacial Gain","value":"Up to +25%"},{"label":"Cell Type","value":"N-Type Bifacial"},{"label":"Glass","value":"Dual 2.0mm Tempered"},{"label":"Snow Load","value":"5400 Pa"},{"label":"Warranty","value":"30 Year Linear"}]'::jsonb, '[{"label":"Output","value":"550W"},{"label":"Gain","value":"+25%"},{"label":"Load","value":"5400Pa"}]'::jsonb, '/images/products/panel-bifacial.svg', '["/images/products/panel-bifacial.svg","/images/products/panel-detail.svg"]'::jsonb, 80, true),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101004'::uuid, 'shiftbank-pro-28', 'ShiftBank Pro 28', 'batteries'::public.product_category, 'VoltCore Systems', 'High-density LFP rack for small business and industrial loads.', 'Rack-mounted high-density lithium iron phosphate system engineered for commercial and light-industrial continuity. Liquid-cooled thermal management sustains full output in ambient temperatures up to 45°C.', 1480000, null, 4.7, null, true, 12000, 28, '[{"label":"Usable Capacity","value":"28.0 kWh"},{"label":"Nominal Voltage","value":"48V DC"},{"label":"Cooling","value":"Liquid-Cooled"},{"label":"Continuous Output","value":"12.0 kW"},{"label":"Form Factor","value":"19-inch Rack"},{"label":"Warranty","value":"10 Year Commercial"}]'::jsonb, '[{"label":"Capacity","value":"28.0kWh"},{"label":"Voltage","value":"48V DC"},{"label":"Cooling","value":"Liquid"}]'::jsonb, '/images/products/battery-rack.svg', '["/images/products/battery-rack.svg","/images/products/battery-wall.svg"]'::jsonb, 12, false),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101005'::uuid, 'gs-360-compact', 'GS-360 Compact', 'panels'::public.product_category, 'Helios Tech', 'Smaller form factor for complex roof layouts or mobile applications.', 'A compact high-efficiency module designed for constrained roof planes, dormers, and mobile installations. Lightweight anodized frame simplifies single-person handling without sacrificing structural rating.', 31500, null, 4.6, null, true, 360, null, '[{"label":"Peak Power","value":"360 Watts"},{"label":"Efficiency","value":"21.2%"},{"label":"Weight","value":"18 kg (39.7 lbs)"},{"label":"Frame","value":"Anodized Aluminum"},{"label":"Dimensions","value":"1722 × 1134 mm"},{"label":"Warranty","value":"25 Year Linear"}]'::jsonb, '[{"label":"Output","value":"360W"},{"label":"Weight","value":"18kg"},{"label":"Frame","value":"Anodized"}]'::jsonb, '/images/products/panel-compact.svg', '["/images/products/panel-compact.svg","/images/products/panel-detail.svg"]'::jsonb, 200, false),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101006'::uuid, 'gridshift-inverter-7-6', 'GridShift Inverter 7.6', 'inverters'::public.product_category, 'GridShift', 'Smart hybrid inverter with dual MPPT and emergency power supply.', '99.1% CEC-efficient hybrid inverter with integrated rapid shutdown and module-level monitoring. Dual MPPT inputs handle complex array orientations; the integrated EPS port keeps critical circuits live during outages.', 215000, null, 4.9, null, true, 7600, null, '[{"label":"Rated Output","value":"7.6 kW"},{"label":"CEC Efficiency","value":"99.1%"},{"label":"MPPT Inputs","value":"Dual"},{"label":"Phase","value":"Single-Phase"},{"label":"Enclosure","value":"NEMA 4X / IP65"},{"label":"Warranty","value":"12 Year"}]'::jsonb, '[{"label":"Output","value":"7.6kW"},{"label":"Phase","value":"Single"},{"label":"IP","value":"IP65"}]'::jsonb, '/images/products/inverter.svg', '["/images/products/inverter.svg"]'::jsonb, 60, true),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101007'::uuid, 'gridshift-pro-400w', 'GridShift Pro 400W', 'panels'::public.product_category, 'GridShift', 'Precision-engineered monocrystalline module for maximum residential energy yields.', 'The flagship residential module. Precision-engineered N-type monocrystalline cells deliver 21.8% efficiency with an industry-leading 25-year linear power warranty. Ships within 3–5 business days with a free technical consultation included.', 32499, 38900, 4.9, 'HIGH EFFICIENCY', true, 400, null, '[{"label":"Peak Power","value":"400 Watts"},{"label":"Efficiency","value":"21.8%"},{"label":"Cell Type","value":"N-Type Monocrystalline"},{"label":"Weight","value":"21.5 kg (47.4 lbs)"},{"label":"Frame","value":"Anodized Aluminum"},{"label":"Warranty","value":"25 Year Linear"}]'::jsonb, '[{"label":"Output","value":"400W"},{"label":"Efficiency","value":"21.8%"},{"label":"Warranty","value":"25y"}]'::jsonb, '/images/products/panel-pro.svg', '["/images/products/panel-pro.svg","/images/products/panel-detail.svg","/images/products/inverter.svg","/images/products/mounting-kit.svg"]'::jsonb, 150, true),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101008'::uuid, 'vertex-s-440w', 'Vertex-S+ 440W', 'panels'::public.product_category, 'Aether Energy', 'High-efficiency N-type dual glass module built for longevity.', 'Dual-glass N-type construction virtually eliminates micro-crack degradation and PID losses. The Vertex-S+ platform is engineered for high-volume residential arrays where lifetime yield per dollar is the deciding metric.', 26750, null, 4.8, null, true, 440, null, '[{"label":"Peak Power","value":"440 Watts"},{"label":"Efficiency","value":"22.1%"},{"label":"Cell Type","value":"N-Type Dual Glass"},{"label":"Degradation","value":"≤ 0.4% / yr"},{"label":"Frame","value":"Anodized Aluminum"},{"label":"Warranty","value":"25 Year Linear"}]'::jsonb, '[{"label":"Output","value":"440W"},{"label":"Type","value":"N-Type"},{"label":"Glass","value":"Dual"}]'::jsonb, '/images/products/panel-detail.svg', '["/images/products/panel-detail.svg","/images/products/panel-mono.svg"]'::jsonb, 300, false),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101009'::uuid, 'powerbank-10kwh', 'PowerBank 10kWh', 'batteries'::public.product_category, 'VoltCore Systems', 'Standard residential backup with smart load balancing.', 'Wall-mounted residential storage with intelligent load balancing that prioritizes critical circuits automatically. Modular design pairs with any GridShift hybrid inverter.', 549900, null, 4.7, null, true, 5000, 10, '[{"label":"Usable Capacity","value":"10.0 kWh"},{"label":"Continuous Output","value":"5.0 kW"},{"label":"Chemistry","value":"LiFePO4 (LFP)"},{"label":"Mounting","value":"Wall / Floor"},{"label":"Enclosure","value":"IP55"},{"label":"Warranty","value":"10 Year"}]'::jsonb, '[{"label":"Capacity","value":"10kWh"},{"label":"Output","value":"5.0kW"},{"label":"Mount","value":"Wall"}]'::jsonb, '/images/products/battery-wall.svg', '["/images/products/battery-wall.svg"]'::jsonb, 45, false),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101010'::uuid, 'powerbank-max-25kwh', 'PowerBank Max 25kWh', 'batteries'::public.product_category, 'VoltCore Systems', 'Whole-home independence for larger properties and EV charging.', 'Flagship whole-home storage engineered for larger properties with EV charging loads. Dual 7kW output channels allow simultaneous home backup and Level 2 charging during outages.', 1120000, null, 4.9, 'BEST SELLER', true, 14000, 25, '[{"label":"Usable Capacity","value":"25.0 kWh"},{"label":"Continuous Output","value":"14.0 kW"},{"label":"EV Charging","value":"Level 2 Ready"},{"label":"Chemistry","value":"LiFePO4 (LFP)"},{"label":"Scalability","value":"Up to 100 kWh"},{"label":"Warranty","value":"12 Year"}]'::jsonb, '[{"label":"Capacity","value":"25kWh"},{"label":"Output","value":"14kW"},{"label":"EV","value":"Ready"}]'::jsonb, '/images/products/battery-max.svg', '["/images/products/battery-max.svg","/images/products/battery-wall.svg"]'::jsonb, 20, false),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101011'::uuid, 'nano-3kwh', 'Nano 3kWh', 'batteries'::public.product_category, 'Helios Tech', 'Essential backup for small-scale projects and light loads.', 'Compact entry-level storage for cabins, tiny homes, and essential-circuit backup. Plug-and-play commissioning in under 30 minutes with the GridShift mobile app.', 185000, null, 4.5, null, false, 2000, 3, '[{"label":"Usable Capacity","value":"3.0 kWh"},{"label":"Continuous Output","value":"2.0 kW"},{"label":"Chemistry","value":"LiFePO4 (LFP)"},{"label":"Weight","value":"34 kg"},{"label":"Commissioning","value":"App-Guided"},{"label":"Warranty","value":"7 Year"}]'::jsonb, '[{"label":"Capacity","value":"3kWh"},{"label":"Output","value":"2.0kW"},{"label":"Setup","value":"30min"}]'::jsonb, '/images/products/battery-nano.svg', '["/images/products/battery-nano.svg"]'::jsonb, 75, false),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101012'::uuid, 'powergrid-hybrid-inverter-10kw', 'PowerGrid Hybrid Inverter', 'inverters'::public.product_category, 'GridShift', '10kW 3-phase smart system for high-demand properties.', 'Three-phase hybrid inverter for high-demand residential and light-commercial systems. Integrated arc-fault detection, rapid shutdown, and generator input for layered resilience.', 289000, null, 4.8, null, true, 10000, null, '[{"label":"Rated Output","value":"10.0 kW"},{"label":"Phase","value":"Three-Phase"},{"label":"CEC Efficiency","value":"98.8%"},{"label":"MPPT Inputs","value":"Triple"},{"label":"Generator Input","value":"Yes"},{"label":"Warranty","value":"12 Year"}]'::jsonb, '[{"label":"Output","value":"10kW"},{"label":"Phase","value":"Three"},{"label":"Gen","value":"Input"}]'::jsonb, '/images/products/inverter-3phase.svg', '["/images/products/inverter-3phase.svg","/images/products/inverter.svg"]'::jsonb, 30, false),
  ('5f3c1a2e-9b4d-4c6e-8a1f-101010101013'::uuid, 'universal-mounting-hardware', 'Universal Mounting Hardware', 'accessories'::public.product_category, 'GridShift', 'Roof-specific kit for 16 panels with rail-free installation.', 'Complete roof-specific mounting set for arrays up to 16 modules. Aerospace-grade aluminum with pre-assembled flashing achieves a fully sealed penetration in a single step.', 84000, null, 4.7, null, false, null, null, '[{"label":"Array Coverage","value":"Up to 16 Modules"},{"label":"Material","value":"Aluminum 6005-T5"},{"label":"Wind Rating","value":"140 mph"},{"label":"Roof Types","value":"Comp / Tile / Metal"},{"label":"Flashing","value":"Pre-Assembled"},{"label":"Warranty","value":"25 Year"}]'::jsonb, '[{"label":"Coverage","value":"16 Panels"},{"label":"Material","value":"AL 6005-T5"},{"label":"Wind","value":"140mph"}]'::jsonb, '/images/products/mounting-kit.svg', '["/images/products/mounting-kit.svg"]'::jsonb, 90, false)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  manufacturer = excluded.manufacturer,
  tagline = excluded.tagline,
  description = excluded.description,
  price_cents = excluded.price_cents,
  compare_at_price_cents = excluded.compare_at_price_cents,
  rating = excluded.rating,
  badge = excluded.badge,
  tax_credit_eligible = excluded.tax_credit_eligible,
  power_output_w = excluded.power_output_w,
  capacity_kwh = excluded.capacity_kwh,
  specs = excluded.specs,
  key_specs = excluded.key_specs,
  image = excluded.image,
  images = excluded.images,
  stock = excluded.stock,
  featured = excluded.featured;
